// admin-loader.js - Scripts usados pela página de configurações/admin
CadimusPageLoader.carregar([
  "api-client.js?v=101",
  "auth-api.js?v=100",
  "notifications-api.js?v=100",
  "wallets-api.js?v=100",
  "entries-api.js?v=100",
  "admin-api.js?v=100",
  "cards-api.js?v=100",
  "budgets-api.js?v=100",
  "goals-api.js?v=100",
  "scheduled-api.js?v=100",
  "app-version.js?v=101",
  "app-footer-component.js?v=101",
  "auth-session.js?v=100",
  "auth.js?v=126",
  "ui-formatters.js?v=100",
  "money-utils.js?v=100",
  "money-ui.js?v=100",
  "components.js?v=105",
  "ui-feedback.js?v=100",
  "ui-theme.js?v=100",
  "ui-pwa.js?v=100",
  "ui-core.js?v=113",
  "ui-bootstrap.js?v=102",
  "wallets-ui.js?v=117",
  "pages/entries/entries-state.js?v=100",
  "notifications-ui.js?v=100",
  "admin-shell-ui.js?v=101",
  "admin-settings-ui.js?v=103",
  "profile-image-ui.js?v=100",
  "admin-users-ui.js?v=102",
  "admin-categories-ui.js?v=101",
  "fixed-expenses-ui.js?v=111",
  "installments-ui.js?v=110",
  "budgets-ui.js?v=102",
  "goals-ui.js?v=101",
  "admin-page-bootstrap.js?v=100",
  { src: "recorrentes.js?v=105", defer: true },
  { src: "bonuses-ui.js?v=104", defer: true },
]);

