// planning-loader.js - Scripts usados pela página de planejamento
CadimusPageLoader.carregar([
  "api-client.js?v=101",
  "auth-api.js?v=100",
  "planning-api.js?v=100",
  "notifications-api.js?v=100",
  "wallets-api.js?v=100",
  "entries-api.js?v=100",
  "admin-api.js?v=100",
  "cards-api.js?v=100",
  "budgets-api.js?v=100",
  "goals-api.js?v=100",
  "scheduled-api.js?v=100",
  "app-footer-component.js?v=100",
  "auth.js?v=121",
  "ui-formatters.js?v=100",
  "money-utils.js?v=100",
  "money-ui.js?v=100",
  "components.js?v=104",
  "ui-core.js?v=106",
  "wallets-ui.js?v=113",
  "categories-ui.js?v=100",
  "entries-modal-ui.js?v=118",
  "entries-loader-ui.js?v=108",
  "fixed-expenses-ui.js?v=108",
  "installments-ui.js?v=107",
  "budgets-ui.js?v=102",
  "goals-ui.js?v=101",
  "planning-shell-ui.js?v=106",
  "planning-dashboard-ui.js?v=104",
  "planning-plans-ui.js?v=100",
  "planning-goals-ui.js?v=100",
  { src: "bonuses-ui.js?v=104", defer: true },
]);

